### ISSUE TITLE
npm install 時のエラー

### ISSUE THREAD

**Issue by TabeteSuguneru** [mtmtkj/okr_laravel#52]
> $ npm install

したら以下のエラーがでた。

```
[root@d4d755bf925b html]# npm -v
module.js:491
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
[root@d4d755bf925b html]# node -v
v8.4.0
```

**Comment by TabeteSuguneru** [comment]
>$ n latest
で解決した。
